# Generated by Django 4.0.1 on 2022-01-25 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20, null=True)),
                ('destination_address', models.CharField(max_length=200)),
                ('driver_id', models.CharField(max_length=20, null=True)),
                ('arrival_data_time', models.DateTimeField()),
                ('number_passengers', models.IntegerField()),
                ('is_shared', models.BooleanField()),
                ('completed_status', models.IntegerField()),
                ('Other', models.CharField(max_length=300, null=True)),
                ('owner_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('license_plate_number', models.CharField(max_length=50)),
                ('max_number_passengers', models.IntegerField(default=0)),
                ('others', models.CharField(max_length=300, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookaride.request')),
                ('sharer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookaride.vehicle'),
        ),
    ]
