# Generated by Django 4.0.1 on 2022-01-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookaride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelist',
            name='number_passengers',
            field=models.IntegerField(default=1),
        ),
    ]
