# Generated by Django 4.0.1 on 2022-01-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookaride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20)),
                ('destination_address', models.CharField(max_length=200)),
                ('arrival_data_time', models.DateTimeField()),
                ('number_passengers', models.IntegerField()),
                ('is_shared', models.BooleanField()),
                ('completed_status', models.IntegerField()),
                ('Other', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('license_plate_number', models.CharField(max_length=50)),
                ('max_number_passengers', models.IntegerField(default=0)),
                ('others', models.CharField(max_length=300)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookaride.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShareList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookaride.request')),
                ('sharer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookaride.user')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='owner_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookaride.user'),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookaride.vehicle'),
        ),
    ]
