# Generated by Django 4.0.1 on 2022-01-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookaride', '0002_sharelist_number_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='number_passengers_total',
            field=models.IntegerField(default=1),
        ),
    ]
