# Generated by Django 4.0.1 on 2022-01-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookaride', '0003_alter_request_owner_info_alter_sharelist_sharer_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Other',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookaride.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='others',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
