# Generated by Django 4.0.1 on 2022-01-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookaride', '0003_alter_request_owner_info_alter_sharelist_sharer_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Other',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
