# Generated by Django 4.0.1 on 2022-01-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookaride', '0004_alter_request_other_alter_request_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='vehicle_info',
        ),
        migrations.AddField(
            model_name='request',
            name='driver_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
